export { default as Header } from './Header'
export { default as Body } from './Body'
export { default as Home } from './Home'
export { default as Detail } from './Detail'
export { default as Watch } from './watch'
export { default as Episode } from './Episode'
